Design a **Processing Logic configuration view** for a data transformation platform. The UI must integrate seamlessly with the **existing product theme and design system**, so do not introduce new colors, fonts, or visual styles. Reuse existing components, spacing, typography, and glass/neon styling already present in the interface.

The purpose of this screen is to allow users to define **processing logic using natural-language instructions**, while the backend automatically generates the **JSON configuration for execution**.

Example user instruction:

"Populate the Member tag in XML according to the 2000 loop in EDI 834."

The UI must clearly show three things simultaneously:

1. High-level **source structure (EDI)**
2. The **logic instruction**
3. High-level **target structure (XML or JSON)**

Only **loop-level and tag-level hierarchy** should be displayed to keep the interface simple.

---

Layout structure:

Create a **three-panel workspace layout**.

Left panel
Source file structure preview (EDI)

Center panel
Processing logic definition

Right panel
Target structure preview and generated configuration

Panels should be resizable.

---

Source Structure Panel (EDI)

Display a **tree structure of the EDI file hierarchy**.

Only show:

ISA
GS
ST
Loop levels such as:

1000A
1000B
2000
2100

The tree should show **loop and segment names only**, not element-level details.

Users should be able to **expand and collapse loops**.

Selecting a loop highlights where logic applies.

---

Processing Logic Panel

Provide a **natural language logic editor**.

Users can type instructions such as:

"Populate the Member tag in XML according to the 2000 loop in EDI 834."

Below the editor, show **interpreted logic rules generated by the system**.

Example generated rule:

Source: EDI Loop 2000
Target: XML Member
Operation: Create node for each loop instance

Display each rule as a **logic card** that can be edited or confirmed.

---

Target Structure Panel

Display the **target file structure preview**.

For XML:

Members
Member
MemberID
Name
Address

For JSON:

members
member
memberId
name
address

Only **tag-level hierarchy should be shown**.

The goal is to give users a **high-level structural view**, not raw payload data.

---

Backend Configuration Preview

Within the right panel, include a **collapsible configuration preview section** that displays the generated backend JSON.

Example:

{
"processing_rule": {
"source_loop": "2000",
"target_tag": "Member",
"operation": "populate_node"
}
}

This preview is **read-only**, intended for transparency.

---

Structure Synchronization

When a loop is selected in the EDI tree:

Highlight the corresponding target node.

Example:

Selecting Loop 2000 highlights:

Member

This helps users understand the transformation relationship.

---

High-Level Structure Mode

Add a toggle:

High-Level Structure
Detailed Structure

Default mode should be **High-Level**, showing only loops and tags.

---

Rule Execution Flow

Visually represent the transformation flow:

EDI Loop → Processing Rule → Target Tag

Use subtle connectors or flow indicators consistent with the existing UI system.

---

Performance Goal

The UI must allow users to quickly understand and configure **complex transformations without reading raw EDI or XML files**.

The interface should feel like **supervising an intelligent transformation engine rather than manually writing configurations**.

---

Components to generate

EDIStructureTree
ProcessingLogicEditor
LogicRuleCard
TargetStructureTree
BackendJSONPreview
StructureSyncHighlighter
