import React, { useState, useCallback, useMemo, useEffect, useRef } from "react";
import { PanelGroup, Panel, PanelResizeHandle } from "react-resizable-panels";
import {
  ChevronRight, ChevronDown, CheckCircle2, Edit3, X,
  Terminal, Layers, Sparkles, Code2, ArrowRight,
  FileCode2, Zap, Play, Eye, ArrowRightLeft, Copy, Check,
} from "lucide-react";

// ─── Design tokens ───────────────────────────────────────────────────────────
const C = {
  bg:          "var(--c-bg)",
  bg2:         "var(--c-bg2)",
  glassBg:     "var(--c-glass-bg)",
  glassBorder: "var(--c-glass-border)",
  border:      "var(--c-border)",
  borderMed:   "var(--c-border-med)",
  text:        "var(--c-text)",
  sub:         "var(--c-sub)",
  muted:       "var(--c-muted)",
  em:          "#10B981",
  em2:         "#34D399",
  emDim:       "rgba(16,185,129,0.14)",
  emGlow:      "var(--c-em-glow)",
  emTextGlow:  "var(--c-em-text-glow)",
  info:        "#3B82F6",
  infoDim:     "rgba(59,130,246,0.12)",
  purple:      "#8B5CF6",
  purpleDim:   "rgba(139,92,246,0.12)",
  warn:        "#F59E0B",
  err:         "#EF4444",
};

// ─── Sample EDI 834 raw content ──────────────────────────────────────────────
const SAMPLE_EDI = `ISA*00*          *00*          *ZZ*SENDER123      *ZZ*RECEIVER456    *260316*0900*^*00501*000000001*0*P*:~
GS*BE*SENDER123*RECEIVER456*20260316*0900*1*X*005010X220A1~
ST*834*0001*005010X220A1~
BGN*00*12345*20260316*090000*ET***2~
REF*38*PLAN001~
DTP*307*D8*20260101~
N1*P5*ACME HEALTH PLAN*FI*123456789~
N3*100 HEALTH PLAZA~
N4*CHICAGO*IL*60601~
N1*IN*PREMIER INSURANCE CO*XV*987654321~
N3*200 INSURANCE BLVD~
N4*DALLAS*TX*75201~
INS*Y*18*030*XN*A*E**FT~
REF*0F*MBR-001-JOHNSON~
REF*1L*GRP-2026-ACME~
DTP*356*D8*20260101~
NM1*IL*1*JOHNSON*ROBERT*A***34*123-45-6789~
PER*IP**TE*3125550101~
N3*742 EVERGREEN TERRACE~
N4*SPRINGFIELD*IL*62701~
DMG*D8*19820315*M~
HD*030**HLT*PLAN001*IND~
DTP*348*D8*20260101~
INS*N*01*030*XN*A*E**FT~
REF*0F*MBR-002-JOHNSON~
DTP*356*D8*20260101~
NM1*IL*1*JOHNSON*EMILY*R***34*234-56-7890~
PER*IP**TE*3125550102~
N3*742 EVERGREEN TERRACE~
N4*SPRINGFIELD*IL*62701~
DMG*D8*19850720*F~
HD*030**HLT*PLAN001*IND~
DTP*348*D8*20260101~
INS*N*19*030*XN*A*E**FT~
REF*0F*MBR-003-SMITH~
DTP*356*D8*20260101~
NM1*IL*1*SMITH*DAVID*M***34*345-67-8901~
PER*IP**TE*2145550103~
N3*1600 PENNSYLVANIA AVE~
N4*DALLAS*TX*75201~
DMG*D8*19901105*M~
HD*030**HLT*PLAN001*IND~
DTP*348*D8*20260101~
SE*42*0001~
GE*1*1~
IEA*1*000000001~`;

// ─── Generated XML output ────────────────────────────────────────────────────
const GENERATED_XML = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Nexus Pipeline v4.0 — EDI 834 → XML -->
<!-- Processing timestamp: 2026-03-16T09:00:00Z        -->
<!-- Source: ISA*000000001 | Rules applied: 3 confirmed -->
<Members>

  <!-- ═══ ENVELOPE ══════════════════════════════════════ -->
  <Interchange>
    <SenderId>SENDER123</SenderId>
    <ReceiverId>RECEIVER456</ReceiverId>
    <InterchangeDate>2026-03-16</InterchangeDate>
    <InterchangeTime>09:00</InterchangeTime>
    <ControlNumber>000000001</ControlNumber>
  </Interchange>

  <!-- ═══ SPONSOR — Loop 1000A ══════════════════════════ -->
  <Sponsor>
    <Name>ACME HEALTH PLAN</Name>
    <IdCode>123456789</IdCode>
    <Address>
      <Street>100 HEALTH PLAZA</Street>
      <City>CHICAGO</City>
      <State>IL</State>
      <Zip>60601</Zip>
    </Address>
  </Sponsor>

  <!-- ═══ PAYER — Loop 1000B ════════════════════════════ -->
  <Payer>
    <Name>PREMIER INSURANCE CO</Name>
    <IdCode>987654321</IdCode>
    <Address>
      <Street>200 INSURANCE BLVD</Street>
      <City>DALLAS</City>
      <State>TX</State>
      <Zip>75201</Zip>
    </Address>
  </Payer>

  <!-- ═══ MEMBERS — Loop 2000 ███████████████████████████ -->

  <!-- Member 1: ROBERT A JOHNSON -->
  <Member>
    <MemberID>MBR-001-JOHNSON</MemberID>
    <GroupId>GRP-2026-ACME</GroupId>
    <SubscriberIndicator>Y</SubscriberIndicator>
    <EffectiveDate>2026-01-01</EffectiveDate>
    <!-- Loop 2100 — NM1 ·· Member Name -->
    <Name>
      <LastName>JOHNSON</LastName>
      <FirstName>ROBERT</FirstName>
      <MiddleInitial>A</MiddleInitial>
      <SSN>123-45-6789</SSN>
    </Name>
    <!-- Loop 2100 — N3/N4 ·· Member Address -->
    <Address>
      <Street>742 EVERGREEN TERRACE</Street>
      <City>SPRINGFIELD</City>
      <State>IL</State>
      <Zip>62701</Zip>
    </Address>
    <!-- Loop 2100 — DMG ·· Demographics -->
    <Demographics>
      <DateOfBirth>1982-03-15</DateOfBirth>
      <Gender>M</Gender>
    </Demographics>
    <Contact>
      <Phone>312-555-0101</Phone>
    </Contact>
    <Coverage>
      <PlanId>PLAN001</PlanId>
      <CoverageType>HLT</CoverageType>
      <CoverageLevel>IND</CoverageLevel>
      <StartDate>2026-01-01</StartDate>
    </Coverage>
  </Member>

  <!-- Member 2: EMILY R JOHNSON -->
  <Member>
    <MemberID>MBR-002-JOHNSON</MemberID>
    <SubscriberIndicator>N</SubscriberIndicator>
    <EffectiveDate>2026-01-01</EffectiveDate>
    <Name>
      <LastName>JOHNSON</LastName>
      <FirstName>EMILY</FirstName>
      <MiddleInitial>R</MiddleInitial>
      <SSN>234-56-7890</SSN>
    </Name>
    <Address>
      <Street>742 EVERGREEN TERRACE</Street>
      <City>SPRINGFIELD</City>
      <State>IL</State>
      <Zip>62701</Zip>
    </Address>
    <Demographics>
      <DateOfBirth>1985-07-20</DateOfBirth>
      <Gender>F</Gender>
    </Demographics>
    <Contact>
      <Phone>312-555-0102</Phone>
    </Contact>
    <Coverage>
      <PlanId>PLAN001</PlanId>
      <CoverageType>HLT</CoverageType>
      <CoverageLevel>IND</CoverageLevel>
      <StartDate>2026-01-01</StartDate>
    </Coverage>
  </Member>

  <!-- Member 3: DAVID M SMITH -->
  <Member>
    <MemberID>MBR-003-SMITH</MemberID>
    <SubscriberIndicator>N</SubscriberIndicator>
    <EffectiveDate>2026-01-01</EffectiveDate>
    <Name>
      <LastName>SMITH</LastName>
      <FirstName>DAVID</FirstName>
      <MiddleInitial>M</MiddleInitial>
      <SSN>345-67-8901</SSN>
    </Name>
    <Address>
      <Street>1600 PENNSYLVANIA AVE</Street>
      <City>DALLAS</City>
      <State>TX</State>
      <Zip>75201</Zip>
    </Address>
    <Demographics>
      <DateOfBirth>1990-11-05</DateOfBirth>
      <Gender>M</Gender>
    </Demographics>
    <Contact>
      <Phone>214-555-0103</Phone>
    </Contact>
    <Coverage>
      <PlanId>PLAN001</PlanId>
      <CoverageType>HLT</CoverageType>
      <CoverageLevel>IND</CoverageLevel>
      <StartDate>2026-01-01</StartDate>
    </Coverage>
  </Member>

</Members>`;

// ─── Syntax-highlighted EDI line ─────────────────────────────────────────────
function EDILine({ line, lineNum }: { line: string; lineNum: number }) {
  if (!line.trim()) return (
    <div className="flex">
      <span style={{ width: 38, color: "rgba(255,255,255,0.15)", fontSize: "0.65rem", userSelect: "none", flexShrink: 0, textAlign: "right", paddingRight: 14 }}>{lineNum}</span>
    </div>
  );

  const parts = line.replace(/~$/, "").split("*");
  const seg   = parts[0];
  const elems = parts.slice(1);

  const segColor: Record<string, string> = {
    ISA: "#3B82F6", GS: "#3B82F6", ST: "#3B82F6", SE: "#3B82F6", GE: "#3B82F6", IEA: "#3B82F6",
    BGN: "#F59E0B", REF: "#F59E0B", DTP: "#F59E0B",
    N1: "#8B5CF6", N3: "#8B5CF6", N4: "#8B5CF6",
    INS: "#10B981", NM1: "#10B981", PER: "#10B981", DMG: "#10B981", HD: "#10B981",
  };
  const color = segColor[seg] ?? "#94A3B8";

  return (
    <div className="flex hover:bg-white/[0.03] rounded transition-colors">
      <span style={{ width: 38, color: "rgba(255,255,255,0.15)", fontSize: "0.65rem", userSelect: "none", flexShrink: 0, textAlign: "right", paddingRight: 14, lineHeight: "1.7" }}>
        {lineNum}
      </span>
      <span className="font-mono" style={{ fontSize: "0.72rem", lineHeight: "1.7" }}>
        <span style={{ color, fontWeight: 700 }}>{seg}</span>
        {elems.map((el, i) => (
          <span key={i}>
            <span style={{ color: "rgba(255,255,255,0.25)" }}>*</span>
            <span style={{ color: el.trim() === "" ? "rgba(255,255,255,0.18)" : "#CBD5E1" }}>{el || "·"}</span>
          </span>
        ))}
        <span style={{ color: "rgba(16,185,129,0.55)", fontWeight: 700 }}>~</span>
      </span>
    </div>
  );
}

// ─── Syntax-highlighted XML line ─────────────────────────────────────────────
function XMLLine({ line, lineNum }: { line: string; lineNum: number }) {
  if (!line.trim()) return (
    <div className="flex">
      <span style={{ width: 38, color: "rgba(255,255,255,0.15)", fontSize: "0.65rem", userSelect: "none", flexShrink: 0, textAlign: "right", paddingRight: 14 }}>{lineNum}</span>
    </div>
  );

  const isComment = line.trim().startsWith("<!--");
  const isDecl    = line.trim().startsWith("<?");
  const isClose   = /^\s*<\//.test(line);

  // Tokenize XML for coloring
  function colorize(raw: string): React.ReactNode[] {
    const tokens: React.ReactNode[] = [];
    let rest = raw;
    let key  = 0;

    while (rest.length) {
      // comment
      const cm = rest.match(/^(<!--.*?-->)([\s\S]*)/);
      if (cm) { tokens.push(<span key={key++} style={{ color: "#475569", fontStyle: "italic" }}>{cm[1]}</span>); rest = cm[2]; continue; }
      // decl
      const dc = rest.match(/^(<\?.*?\?>)([\s\S]*)/);
      if (dc) { tokens.push(<span key={key++} style={{ color: "#64748B" }}>{dc[1]}</span>); rest = dc[2]; continue; }
      // closing tag
      const ct = rest.match(/^(<\/)([\w:.-]+)(>)([\s\S]*)/);
      if (ct) {
        tokens.push(<span key={key++} style={{ color: "#475569" }}>{ct[1]}</span>);
        tokens.push(<span key={key++} style={{ color: "#34D399" }}>{ct[2]}</span>);
        tokens.push(<span key={key++} style={{ color: "#475569" }}>{ct[3]}</span>);
        rest = ct[4]; continue;
      }
      // opening tag
      const ot = rest.match(/^(<)([\w:.-]+)((?:\s[\w:.-]+="[^"]*")*)\s*(\/?>)([\s\S]*)/);
      if (ot) {
        tokens.push(<span key={key++} style={{ color: "#475569" }}>{ot[1]}</span>);
        tokens.push(<span key={key++} style={{ color: "#10B981", fontWeight: 700 }}>{ot[2]}</span>);
        // attrs
        const attrStr = ot[3];
        if (attrStr) {
          const attrParts = attrStr.match(/[\w:.-]+="[^"]*"/g) ?? [];
          attrParts.forEach(a => {
            const [aName, aVal] = a.split("=");
            tokens.push(<span key={key++}> <span style={{ color: "#93C5FD" }}>{aName}</span><span style={{ color: "#475569" }}>=</span><span style={{ color: "#F59E0B" }}>"{aVal?.replace(/"/g, "")}"</span></span>);
          });
        }
        tokens.push(<span key={key++} style={{ color: "#475569" }}>{ot[4]}</span>);
        rest = ot[5]; continue;
      }
      // text / rest
      const tx = rest.match(/^([^<]+)([\s\S]*)/);
      if (tx) { tokens.push(<span key={key++} style={{ color: "#E2E8F0" }}>{tx[1]}</span>); rest = tx[2]; continue; }
      tokens.push(<span key={key++} style={{ color: "#94A3B8" }}>{rest}</span>);
      break;
    }
    return tokens;
  }

  return (
    <div className="flex hover:bg-white/[0.03] rounded transition-colors">
      <span style={{ width: 38, color: "rgba(255,255,255,0.15)", fontSize: "0.65rem", userSelect: "none", flexShrink: 0, textAlign: "right", paddingRight: 14, lineHeight: "1.7" }}>
        {lineNum}
      </span>
      <span className="font-mono" style={{ fontSize: "0.72rem", lineHeight: "1.7" }}>
        {colorize(line)}
      </span>
    </div>
  );
}

// ─── Copy Button ─────────────────────────────────────────────────────────────
function CopyBtn({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const copy = () => {
    navigator.clipboard.writeText(text).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button
      onClick={copy}
      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg font-mono transition-all hover:scale-105"
      style={{
        background: copied ? C.emDim : C.glassBg,
        border: `1px solid ${copied ? "rgba(16,185,129,0.38)" : C.glassBorder}`,
        color: copied ? C.em : C.muted, fontSize: "0.62rem", fontWeight: 700,
      }}
    >
      {copied ? <Check style={{ width: 11, height: 11 }} /> : <Copy style={{ width: 11, height: 11 }} />}
      {copied ? "Copied!" : "Copy"}
    </button>
  );
}

// ─── Translation Preview Overlay ─────────────────────────────────────────────
function TranslationPreviewOverlay({
  targetFormat, onClose,
}: { targetFormat: "XML" | "JSON"; onClose: () => void }) {
  const [scanning, setScanning]     = useState(true);
  const [progress, setProgress]     = useState(0);
  const [showOutput, setShowOutput] = useState(false);
  const [activePane, setActivePane] = useState<"split" | "input" | "output">("split");
  const ediRef  = useRef<HTMLDivElement>(null);
  const xmlRef  = useRef<HTMLDivElement>(null);

  // Simulated "processing" animation on mount
  useEffect(() => {
    let p = 0;
    const iv = setInterval(() => {
      p += Math.random() * 18 + 8;
      if (p >= 100) { p = 100; clearInterval(iv); setScanning(false); setShowOutput(true); }
      setProgress(Math.min(p, 100));
    }, 80);
    return () => clearInterval(iv);
  }, []);

  // Escape key to close
  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose]);

  const ediLines  = SAMPLE_EDI.split("\n");
  const xmlOutput = targetFormat === "JSON"
    ? JSON.stringify({
        members: [
          {
            memberId: "MBR-001-JOHNSON", name: { last: "JOHNSON", first: "ROBERT", mi: "A" },
            ssn: "123-45-6789", dob: "1982-03-15", gender: "M",
            address: { street: "742 EVERGREEN TERRACE", city: "SPRINGFIELD", state: "IL", zip: "62701" },
            coverage: { planId: "PLAN001", type: "HLT", level: "IND", startDate: "2026-01-01" },
          },
          {
            memberId: "MBR-002-JOHNSON", name: { last: "JOHNSON", first: "EMILY", mi: "R" },
            ssn: "234-56-7890", dob: "1985-07-20", gender: "F",
            address: { street: "742 EVERGREEN TERRACE", city: "SPRINGFIELD", state: "IL", zip: "62701" },
            coverage: { planId: "PLAN001", type: "HLT", level: "IND", startDate: "2026-01-01" },
          },
          {
            memberId: "MBR-003-SMITH", name: { last: "SMITH", first: "DAVID", mi: "M" },
            ssn: "345-67-8901", dob: "1990-11-05", gender: "M",
            address: { street: "1600 PENNSYLVANIA AVE", city: "DALLAS", state: "TX", zip: "75201" },
            coverage: { planId: "PLAN001", type: "HLT", level: "IND", startDate: "2026-01-01" },
          },
        ],
      }, null, 2)
    : GENERATED_XML;

  const xmlLines = xmlOutput.split("\n");

  const stats = [
    { label: "EDI Segments", val: ediLines.filter(l => l.trim() && !l.startsWith("//")).length },
    { label: "Members Extracted", val: "3" },
    { label: "Rules Applied", val: "3" },
    { label: "Output Lines", val: xmlLines.length },
    { label: "Format", val: targetFormat },
    { label: "Status", val: "SUCCESS", em: true },
  ];

  return (
    <div
      style={{
        position: "fixed", inset: 0, zIndex: 9999,
        background: "rgba(7,12,24,0.88)",
        backdropFilter: "blur(18px)",
        WebkitBackdropFilter: "blur(18px)",
        display: "flex", flexDirection: "column",
      }}
    >
      {/* ── Scanning animation overlay ── */}
      {scanning && (
        <div
          style={{
            position: "absolute", inset: 0, zIndex: 10,
            display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
            background: "rgba(7,12,24,0.92)",
          }}
        >
          {/* Animated scan line */}
          <div style={{ position: "relative", width: 440, height: 280, marginBottom: 40 }}>
            <div
              style={{
                position: "absolute", inset: 0,
                background: "rgba(16,185,129,0.04)",
                border: "1px solid rgba(16,185,129,0.20)",
                borderRadius: 20,
                overflow: "hidden",
              }}
            >
              {/* Simulated EDI lines in background */}
              {["ISA*00*...", "GS*BE*SENDER...", "ST*834*0001...", "INS*Y*18*030...", "NM1*IL*1*JOHNSON...", "N3*742 EVERGREEN...", "DMG*D8*19820315*M~"].map((l, i) => (
                <div
                  key={i}
                  className="font-mono px-6"
                  style={{
                    fontSize: "0.7rem", lineHeight: "1.9",
                    color: `rgba(16,185,129,${0.08 + i * 0.03})`,
                    marginTop: i === 0 ? 20 : 0,
                  }}
                >
                  {l}
                </div>
              ))}
              {/* Scan sweep */}
              <div
                style={{
                  position: "absolute", left: 0, right: 0, height: 2,
                  background: `linear-gradient(90deg, transparent, ${C.em}, transparent)`,
                  boxShadow: `0 0 20px ${C.em}`,
                  top: `${progress}%`,
                  transition: "top 0.08s linear",
                }}
              />
            </div>
          </div>

          <div className="flex items-center gap-3 mb-4">
            <div className="w-5 h-5 rounded-full border-2 animate-spin" style={{ borderColor: `rgba(16,185,129,0.25)`, borderTopColor: C.em }} />
            <span className="font-mono" style={{ color: C.em, fontSize: "0.78rem", fontWeight: 700, letterSpacing: "0.08em" }}>
              TRANSLATING EDI 834 → {targetFormat}
            </span>
          </div>

          {/* Progress bar */}
          <div style={{ width: 440, height: 4, background: "rgba(16,185,129,0.12)", borderRadius: 4, overflow: "hidden" }}>
            <div
              style={{
                height: "100%", width: `${progress}%`,
                background: `linear-gradient(90deg, ${C.em}, ${C.em2})`,
                boxShadow: `0 0 8px ${C.em}`,
                transition: "width 0.08s linear", borderRadius: 4,
              }}
            />
          </div>
          <span className="font-mono mt-2" style={{ color: C.muted, fontSize: "0.65rem" }}>
            {Math.round(progress)}% — Applying processing rules…
          </span>
        </div>
      )}

      {/* ── Header ── */}
      <div
        className="flex items-center gap-3 px-6 py-4 flex-shrink-0"
        style={{ borderBottom: `1px solid rgba(255,255,255,0.08)`, background: "rgba(11,18,32,0.7)" }}
      >
        {/* Icon + title */}
        <div
          className="flex items-center justify-center rounded-xl flex-shrink-0"
          style={{ width: 36, height: 36, background: C.emDim, border: `1px solid rgba(16,185,129,0.30)` }}
        >
          <ArrowRightLeft style={{ width: 16, height: 16, color: C.em }} />
        </div>
        <div>
          <div className="font-mono" style={{ color: C.text, fontSize: "0.85rem", fontWeight: 700 }}>
            Translation Preview
          </div>
          <div className="font-mono" style={{ color: C.muted, fontSize: "0.62rem" }}>
            EDI X12 834 → {targetFormat} · Sample file
          </div>
        </div>

        {/* Stats pills */}
        <div className="flex items-center gap-2 ml-6">
          {stats.map(s => (
            <div
              key={s.label}
              className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg"
              style={{
                background: s.em ? C.emDim : "rgba(255,255,255,0.04)",
                border: `1px solid ${s.em ? "rgba(16,185,129,0.35)" : "rgba(255,255,255,0.08)"}`,
              }}
            >
              <span className="font-mono" style={{ color: C.muted, fontSize: "0.58rem" }}>{s.label}</span>
              <span
                className="font-mono"
                style={{
                  color: s.em ? C.em : C.sub, fontSize: "0.62rem", fontWeight: 700,
                  textShadow: s.em ? C.emTextGlow : undefined,
                }}
              >
                {s.val}
              </span>
            </div>
          ))}
        </div>

        {/* View mode pills */}
        <div className="ml-auto flex items-center gap-2">
          <div
            className="flex items-center gap-0.5 rounded-lg p-0.5"
            style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}
          >
            {(["split", "input", "output"] as const).map(m => (
              <button
                key={m}
                onClick={() => setActivePane(m)}
                className="font-mono rounded-md px-3 py-1.5 transition-all capitalize"
                style={{
                  background: activePane === m ? "rgba(16,185,129,0.14)" : "transparent",
                  border: activePane === m ? "1px solid rgba(16,185,129,0.35)" : "1px solid transparent",
                  color: activePane === m ? C.em : C.muted,
                  fontSize: "0.62rem", fontWeight: 700,
                }}
              >
                {m}
              </button>
            ))}
          </div>

          <button
            onClick={onClose}
            className="flex items-center justify-center rounded-xl transition-all hover:scale-110"
            style={{
              width: 34, height: 34,
              background: "rgba(239,68,68,0.10)",
              border: "1px solid rgba(239,68,68,0.28)",
              color: C.err,
            }}
            title="Close (Esc)"
          >
            <X style={{ width: 15, height: 15 }} />
          </button>
        </div>
      </div>

      {/* ── Main content ── */}
      <div style={{ flex: 1, display: "flex", minHeight: 0, overflow: "hidden" }}>

        {/* ── EDI INPUT pane ── */}
        {(activePane === "split" || activePane === "input") && (
          <div
            style={{
              flex: activePane === "split" ? "0 0 50%" : "1",
              display: "flex", flexDirection: "column",
              borderRight: activePane === "split" ? `1px solid rgba(59,130,246,0.20)` : "none",
            }}
          >
            {/* Pane header */}
            <div
              className="flex items-center gap-2 px-5 py-3 flex-shrink-0"
              style={{ borderBottom: "1px solid rgba(59,130,246,0.15)", background: "rgba(59,130,246,0.05)" }}
            >
              <FileCode2 style={{ width: 13, height: 13, color: C.info }} />
              <span className="font-mono" style={{ color: C.info, fontSize: "0.68rem", fontWeight: 700, letterSpacing: "0.08em" }}>
                INPUT — EDI X12 834
              </span>
              <span
                className="font-mono ml-2 px-2 py-0.5 rounded"
                style={{
                  background: "rgba(59,130,246,0.10)", border: "1px solid rgba(59,130,246,0.25)",
                  color: C.info, fontSize: "0.55rem", fontWeight: 700,
                }}
              >
                {ediLines.length} SEGMENTS
              </span>
              <div className="ml-auto">
                <CopyBtn text={SAMPLE_EDI} />
              </div>
            </div>

            {/* EDI content */}
            <div
              ref={ediRef}
              className="flex-1 overflow-auto"
              style={{
                background: "rgba(4,9,20,0.60)",
                padding: "14px 12px",
                scrollbarWidth: "thin",
                scrollbarColor: "rgba(59,130,246,0.3) transparent",
              }}
            >
              {ediLines.map((line, i) => (
                <EDILine key={i} line={line} lineNum={i + 1} />
              ))}
            </div>
          </div>
        )}

        {/* ── Flow arrow (split mode) ── */}
        {activePane === "split" && (
          <div
            style={{
              position: "relative", width: 0, display: "flex",
              alignItems: "center", justifyContent: "center", zIndex: 2,
            }}
          >
            <div
              style={{
                position: "absolute",
                background: "rgba(11,18,32,0.95)",
                border: `1px solid rgba(16,185,129,0.35)`,
                borderRadius: 12,
                padding: "6px 10px",
                display: "flex", flexDirection: "column", alignItems: "center", gap: 4,
                boxShadow: `0 0 20px rgba(16,185,129,0.18)`,
              }}
            >
              <Zap style={{ width: 14, height: 14, color: C.em }} />
              <div
                style={{
                  width: 2, height: 18,
                  background: `linear-gradient(${C.em}, ${C.em2})`,
                  borderRadius: 2,
                }}
              />
              <ArrowRight style={{ width: 12, height: 12, color: C.em2 }} />
            </div>
          </div>
        )}

        {/* ── XML/JSON OUTPUT pane ── */}
        {(activePane === "split" || activePane === "output") && (
          <div
            style={{
              flex: activePane === "split" ? "0 0 50%" : "1",
              display: "flex", flexDirection: "column",
            }}
          >
            {/* Pane header */}
            <div
              className="flex items-center gap-2 px-5 py-3 flex-shrink-0"
              style={{
                borderBottom: `1px solid rgba(16,185,129,0.15)`,
                background: "rgba(16,185,129,0.04)",
              }}
            >
              <Code2 style={{ width: 13, height: 13, color: C.em }} />
              <span className="font-mono" style={{ color: C.em, fontSize: "0.68rem", fontWeight: 700, letterSpacing: "0.08em" }}>
                OUTPUT — GENERATED {targetFormat}
              </span>
              {showOutput && (
                <span
                  className="font-mono ml-2 px-2 py-0.5 rounded animate-pulse"
                  style={{
                    background: C.emDim, border: "1px solid rgba(16,185,129,0.35)",
                    color: C.em, fontSize: "0.55rem", fontWeight: 700,
                  }}
                >
                  LIVE
                </span>
              )}
              <span
                className="font-mono px-2 py-0.5 rounded ml-1"
                style={{
                  background: "rgba(16,185,129,0.08)", border: "1px solid rgba(16,185,129,0.20)",
                  color: C.em2, fontSize: "0.55rem", fontWeight: 700,
                }}
              >
                {xmlLines.length} LINES
              </span>
              <div className="ml-auto">
                <CopyBtn text={xmlOutput} />
              </div>
            </div>

            {/* Output content */}
            <div
              ref={xmlRef}
              className="flex-1 overflow-auto"
              style={{
                background: "rgba(4,9,20,0.55)",
                padding: "14px 12px",
                scrollbarWidth: "thin",
                scrollbarColor: "rgba(16,185,129,0.3) transparent",
              }}
            >
              {!showOutput ? (
                /* Skeleton while processing */
                <div className="space-y-1.5 p-2">
                  {Array.from({ length: 18 }).map((_, i) => (
                    <div
                      key={i}
                      className="rounded animate-pulse"
                      style={{
                        height: 13,
                        width: `${40 + Math.sin(i * 1.7) * 30 + 30}%`,
                        background: "rgba(16,185,129,0.07)",
                        marginLeft: i % 3 !== 0 ? 24 : 0,
                      }}
                    />
                  ))}
                </div>
              ) : (
                targetFormat === "JSON"
                  ? xmlLines.map((line, i) => (
                      <div key={i} className="flex hover:bg-white/[0.03] rounded transition-colors">
                        <span style={{ width: 38, color: "rgba(255,255,255,0.15)", fontSize: "0.65rem", userSelect: "none", flexShrink: 0, textAlign: "right", paddingRight: 14, lineHeight: "1.7" }}>
                          {i + 1}
                        </span>
                        <span
                          className="font-mono"
                          style={{ fontSize: "0.72rem", lineHeight: "1.7", color: "#E2E8F0" }}
                          dangerouslySetInnerHTML={{
                            __html: line
                              .replace(/("[\w]+")\s*:/g, '<span style="color:#93C5FD">$1</span>:')
                              .replace(/:\s*(".*?")/g, ': <span style="color:#F59E0B">$1</span>')
                              .replace(/:\s*(true|false|null)/g, ': <span style="color:#C084FC">$1</span>')
                              .replace(/:\s*(\d+)/g, ': <span style="color:#34D399">$1</span>')
                              .replace(/^(\s*)([\[\]{}])/g, '$1<span style="color:rgba(16,185,129,0.7)">$2</span>'),
                          }}
                        />
                      </div>
                    ))
                  : xmlLines.map((line, i) => (
                      <XMLLine key={i} line={line} lineNum={i + 1} />
                    ))
              )}
            </div>
          </div>
        )}
      </div>

      {/* ── Footer ── */}
      <div
        className="flex items-center gap-4 px-6 py-3 flex-shrink-0"
        style={{ borderTop: "1px solid rgba(255,255,255,0.06)", background: "rgba(11,18,32,0.7)" }}
      >
        <div className="flex items-center gap-2">
          <div className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ background: C.em }} />
          <span className="font-mono" style={{ color: C.muted, fontSize: "0.62rem" }}>
            Nexus Pipeline v4.0 — Processing Engine
          </span>
        </div>
        <div className="flex items-center gap-4 ml-auto">
          <span className="font-mono" style={{ color: C.muted, fontSize: "0.62rem" }}>
            Source: <span style={{ color: C.info }}>ISA*000000001</span>
          </span>
          <span className="font-mono" style={{ color: C.muted, fontSize: "0.62rem" }}>
            Applied: <span style={{ color: C.em }}>3 rules</span>
          </span>
          <span className="font-mono" style={{ color: C.muted, fontSize: "0.62rem" }}>
            Members: <span style={{ color: C.em2 }}>3 extracted</span>
          </span>
          <button
            onClick={onClose}
            className="font-mono px-4 py-2 rounded-lg transition-all hover:scale-105"
            style={{
              background: "rgba(255,255,255,0.05)",
              border: `1px solid ${C.glassBorder}`,
              color: C.muted, fontSize: "0.68rem", fontWeight: 600,
            }}
          >
            Close Preview  ·  Esc
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── EDI Tree Data ───────────────────────────────────────────────────────────
interface EDINode {
  id: string;
  name: string;
  type: "envelope" | "loop" | "segment";
  targetMapping?: string;
  children?: EDINode[];
}

const EDI_TREE_DATA: EDINode[] = [
  {
    id: "isa", name: "ISA", type: "envelope",
    children: [
      { id: "isa-sender", name: "ISA06 · Sender ID", type: "segment", targetMapping: "senderId" },
      { id: "isa-receiver", name: "ISA08 · Receiver ID", type: "segment", targetMapping: "receiverId" },
    ],
  },
  {
    id: "gs", name: "GS", type: "envelope",
    children: [{ id: "gs01", name: "GS01 · Functional ID", type: "segment" }],
  },
  {
    id: "st", name: "ST", type: "envelope",
    children: [
      { id: "st01", name: "ST01 · Transaction Set ID", type: "segment" },
      { id: "st02", name: "ST02 · Control Number", type: "segment" },
    ],
  },
  {
    id: "loop-1000a", name: "Loop 1000A", type: "loop",
    children: [
      { id: "nm1-1000a", name: "NM1 · Sponsor Name", type: "segment", targetMapping: "sponsor" },
      { id: "n3-1000a",  name: "N3 · Sponsor Address", type: "segment", targetMapping: "sponsor" },
    ],
  },
  {
    id: "loop-1000b", name: "Loop 1000B", type: "loop",
    children: [
      { id: "nm1-1000b", name: "NM1 · Payer Name", type: "segment", targetMapping: "payer" },
      { id: "n3-1000b",  name: "N3 · Payer Address", type: "segment", targetMapping: "payer" },
    ],
  },
  {
    id: "loop-2000", name: "Loop 2000", type: "loop", targetMapping: "member",
    children: [
      { id: "ins-2000", name: "INS · Member Indicator", type: "segment", targetMapping: "member" },
      { id: "ref-2000", name: "REF · Member Reference", type: "segment", targetMapping: "memberId" },
      { id: "dtp-2000", name: "DTP · Date Range", type: "segment", targetMapping: "member" },
      {
        id: "loop-2100", name: "Loop 2100", type: "loop", targetMapping: "member",
        children: [
          { id: "nm1-2100", name: "NM1 · Member Name", type: "segment", targetMapping: "name" },
          { id: "per-2100", name: "PER · Contact Info", type: "segment", targetMapping: "address" },
          { id: "n3-2100",  name: "N3 · Member Address", type: "segment", targetMapping: "address" },
          { id: "dmg-2100", name: "DMG · Demographics", type: "segment", targetMapping: "memberId" },
        ],
      },
    ],
  },
];

// ─── Target structure ────────────────────────────────────────────────────────
interface TargetNode {
  id: string; name: string;
  type: "root" | "element" | "attribute";
  children?: TargetNode[];
}

const XML_TARGET: TargetNode = {
  id: "root", name: "Members", type: "root",
  children: [{
    id: "member", name: "Member", type: "element",
    children: [
      { id: "memberId", name: "MemberID", type: "element" },
      { id: "name", name: "Name", type: "element" },
      {
        id: "address", name: "Address", type: "element",
        children: [
          { id: "street", name: "Street", type: "attribute" },
          { id: "city",   name: "City",   type: "attribute" },
          { id: "zip",    name: "Zip",    type: "attribute" },
        ],
      },
      { id: "sponsor",    name: "Sponsor",    type: "element" },
      { id: "payer",      name: "Payer",      type: "element" },
      { id: "senderId",   name: "SenderId",   type: "element" },
      { id: "receiverId", name: "ReceiverId", type: "element" },
    ],
  }],
};

const JSON_TARGET: TargetNode = {
  id: "root", name: "members [ ]", type: "root",
  children: [{
    id: "member", name: "member { }", type: "element",
    children: [
      { id: "memberId",   name: "memberId",     type: "attribute" },
      { id: "name",       name: "name",         type: "attribute" },
      {
        id: "address", name: "address { }", type: "element",
        children: [
          { id: "street", name: "street", type: "attribute" },
          { id: "city",   name: "city",   type: "attribute" },
          { id: "zip",    name: "zip",    type: "attribute" },
        ],
      },
      { id: "sponsor",    name: "sponsor",    type: "attribute" },
      { id: "payer",      name: "payer",      type: "attribute" },
      { id: "senderId",   name: "senderId",   type: "attribute" },
      { id: "receiverId", name: "receiverId", type: "attribute" },
    ],
  }],
};

// ─── Logic rules ─────────────────────────────────────────────────────────────
interface LogicRule {
  id: string; source: string; target: string; operation: string;
  confirmed: boolean; sourceLoopId?: string; targetNodeId?: string;
}

const INITIAL_RULES: LogicRule[] = [
  { id: "r1", confirmed: true,  source: "EDI Loop 2000",     target: "XML Member",         operation: "Create node for each loop instance",        sourceLoopId: "loop-2000", targetNodeId: "member" },
  { id: "r2", confirmed: true,  source: "EDI Loop 2100 NM1", target: "XML Member › Name",  operation: "Map NM1 composite name → Name element",     sourceLoopId: "loop-2100", targetNodeId: "name" },
  { id: "r3", confirmed: false, source: "EDI Loop 2100 N3",  target: "XML Member › Address",operation: "Map N3 address segments → Address sub-elements", sourceLoopId: "loop-2100", targetNodeId: "address" },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────
function flattenIds(node: EDINode): string[] {
  return [node.id, ...(node.children?.flatMap(flattenIds) ?? [])];
}
function getTargetMappings(node: EDINode): string[] {
  const own = node.targetMapping ? [node.targetMapping] : [];
  return [...own, ...(node.children?.flatMap(getTargetMappings) ?? [])];
}

// ─── EDI Tree Node ────────────────────────────────────────────────────────────
function EDITreeNode({ node, depth, selectedId, onSelect, highlightIds, detailedMode }: {
  node: EDINode; depth: number; selectedId: string | null;
  onSelect: (id: string) => void; highlightIds: Set<string>; detailedMode: boolean;
}) {
  const [open, setOpen] = useState(depth === 0 || node.type === "loop");
  const hasChildren = (node.children?.length ?? 0) > 0;
  const isSelected  = selectedId === node.id;
  const isHighlighted = highlightIds.has(node.id);
  if (!detailedMode && node.type === "segment") return null;
  const typeColor = node.type === "loop" ? C.em : node.type === "envelope" ? C.info : C.muted;
  return (
    <div>
      <button
        onClick={() => { onSelect(node.id); if (hasChildren) setOpen(o => !o); }}
        className="w-full flex items-center gap-1.5 rounded-lg transition-all text-left"
        style={{
          padding: `5px ${8 + depth * 14}px`,
          background: isSelected ? "rgba(16,185,129,0.14)" : isHighlighted ? "rgba(16,185,129,0.06)" : "transparent",
          border: isSelected ? "1px solid rgba(16,185,129,0.38)" : "1px solid transparent",
          marginBottom: 2,
        }}
      >
        {hasChildren
          ? open ? <ChevronDown style={{ width: 11, height: 11, color: C.muted, flexShrink: 0 }} />
                 : <ChevronRight style={{ width: 11, height: 11, color: C.muted, flexShrink: 0 }} />
          : <span style={{ width: 11, flexShrink: 0 }} />
        }
        <span className="font-mono" style={{ fontSize: "0.68rem", fontWeight: node.type === "loop" ? 700 : 600, color: isSelected ? C.em : isHighlighted ? C.em2 : typeColor, textShadow: isSelected ? C.emTextGlow : undefined }}>
          {node.name}
        </span>
        {node.type === "loop" && (
          <span className="ml-auto font-mono" style={{ fontSize: "0.55rem", fontWeight: 700, background: "rgba(16,185,129,0.1)", border: "1px solid rgba(16,185,129,0.25)", color: C.em, padding: "1px 5px", borderRadius: 4 }}>
            LOOP
          </span>
        )}
      </button>
      {open && hasChildren && (
        <div>
          {node.children!.map(child => (
            <EDITreeNode key={child.id} node={child} depth={depth + 1} selectedId={selectedId} onSelect={onSelect} highlightIds={highlightIds} detailedMode={detailedMode} />
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Target Tree Node ─────────────────────────────────────────────────────────
function TargetTreeNode({ node, depth, highlightIds, detailedMode }: {
  node: TargetNode; depth: number; highlightIds: Set<string>; detailedMode: boolean;
}) {
  const [open, setOpen] = useState(depth <= 1);
  const hasChildren   = (node.children?.length ?? 0) > 0;
  const isHighlighted = highlightIds.has(node.id);
  if (!detailedMode && node.type === "attribute" && depth > 2) return null;
  const typePrefix = node.type === "root" ? "▸ " : node.type === "element" ? "◆ " : "· ";
  return (
    <div>
      <button
        onClick={() => hasChildren && setOpen(o => !o)}
        className="w-full flex items-center gap-1.5 rounded-lg transition-all text-left"
        style={{ padding: `5px ${8 + depth * 14}px`, background: isHighlighted ? "rgba(16,185,129,0.12)" : "transparent", border: isHighlighted ? "1px solid rgba(16,185,129,0.35)" : "1px solid transparent", marginBottom: 2 }}
      >
        {hasChildren
          ? open ? <ChevronDown style={{ width: 11, height: 11, color: C.muted, flexShrink: 0 }} />
                 : <ChevronRight style={{ width: 11, height: 11, color: C.muted, flexShrink: 0 }} />
          : <span style={{ width: 11, flexShrink: 0 }} />
        }
        <span className="font-mono" style={{ fontSize: "0.68rem", fontWeight: node.type !== "attribute" ? 700 : 500, color: isHighlighted ? C.em : node.type === "attribute" ? C.muted : C.sub, textShadow: isHighlighted ? C.emTextGlow : undefined }}>
          <span style={{ color: isHighlighted ? C.em2 : C.muted, marginRight: 3 }}>{typePrefix}</span>{node.name}
        </span>
        {isHighlighted && (
          <span className="ml-auto font-mono" style={{ fontSize: "0.52rem", fontWeight: 700, background: C.emDim, border: "1px solid rgba(16,185,129,0.30)", color: C.em, padding: "1px 5px", borderRadius: 4 }}>
            MAPPED
          </span>
        )}
      </button>
      {open && hasChildren && (
        <div>
          {node.children!.map(child => (
            <TargetTreeNode key={child.id} node={child} depth={depth + 1} highlightIds={highlightIds} detailedMode={detailedMode} />
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Logic Rule Card ──────────────────────────────────────────────────────────
function LogicRuleCard({ rule, onConfirm, onRemove, isHighlighted }: {
  rule: LogicRule; onConfirm: (id: string) => void; onRemove: (id: string) => void; isHighlighted: boolean;
}) {
  return (
    <div
      className="rounded-xl p-3.5 transition-all"
      style={{
        background: isHighlighted ? "rgba(16,185,129,0.1)" : rule.confirmed ? "rgba(16,185,129,0.06)" : C.glassBg,
        border: `1px solid ${isHighlighted ? "rgba(16,185,129,0.45)" : rule.confirmed ? "rgba(16,185,129,0.28)" : C.glassBorder}`,
        boxShadow: isHighlighted ? "0 0 18px rgba(16,185,129,0.12)" : "none",
      }}
    >
      <div className="flex items-center gap-2 mb-2.5">
        <span className="font-mono px-2 py-0.5 rounded" style={{ background: "rgba(59,130,246,0.12)", border: "1px solid rgba(59,130,246,0.28)", color: C.info, fontSize: "0.6rem", fontWeight: 700 }}>{rule.source}</span>
        <div className="flex items-center gap-1">
          <div style={{ width: 16, height: 1, background: C.muted }} />
          <Zap style={{ width: 10, height: 10, color: C.em }} />
          <div style={{ width: 16, height: 1, background: C.muted }} />
        </div>
        <span className="font-mono px-2 py-0.5 rounded" style={{ background: "rgba(16,185,129,0.10)", border: "1px solid rgba(16,185,129,0.28)", color: C.em, fontSize: "0.6rem", fontWeight: 700 }}>{rule.target}</span>
      </div>
      <p style={{ color: C.sub, fontSize: "0.72rem", marginBottom: 10 }}>{rule.operation}</p>
      <div className="flex gap-2 items-center">
        {rule.confirmed
          ? <span className="flex items-center gap-1 font-mono" style={{ color: C.em, fontSize: "0.62rem", fontWeight: 700 }}><CheckCircle2 style={{ width: 11, height: 11 }} /> Confirmed</span>
          : <button onClick={() => onConfirm(rule.id)} className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg font-mono transition-all hover:scale-105" style={{ background: C.emDim, border: "1px solid rgba(16,185,129,0.35)", color: C.em, fontSize: "0.62rem", fontWeight: 700 }}><CheckCircle2 style={{ width: 10, height: 10 }} /> Confirm</button>
        }
        <button onClick={() => onRemove(rule.id)} className="ml-auto flex items-center gap-1 px-2.5 py-1 rounded-lg font-mono" style={{ background: "transparent", border: `1px solid ${C.border}`, color: C.muted, fontSize: "0.62rem" }}>
          <X style={{ width: 9, height: 9 }} /> Remove
        </button>
      </div>
    </div>
  );
}

// ─── Backend JSON Preview ─────────────────────────────────────────────────────
function BackendJSONPreview({ rules, targetFormat }: { rules: LogicRule[]; targetFormat: "XML" | "JSON" }) {
  const [open, setOpen] = useState(true);
  const json = useMemo(() => ({
    schema_version: "1.0", target_format: targetFormat,
    processing_rules: rules.map(r => ({ rule_id: r.id, source_loop: r.source, target_tag: r.target, operation: r.operation.toLowerCase().replace(/ /g, "_"), confirmed: r.confirmed })),
  }), [rules, targetFormat]);
  return (
    <div className="rounded-xl overflow-hidden" style={{ border: "1px solid rgba(16,185,129,0.20)", background: "rgba(4,9,20,0.75)" }}>
      <button onClick={() => setOpen(o => !o)} className="w-full flex items-center gap-2 px-4 py-3" style={{ borderBottom: open ? "1px solid rgba(16,185,129,0.15)" : "none" }}>
        <Terminal style={{ width: 13, height: 13, color: C.em }} />
        <span className="font-mono flex-1 text-left" style={{ color: C.em, fontSize: "0.68rem", fontWeight: 700, letterSpacing: "0.08em" }}>GENERATED CONFIG JSON</span>
        <span className="font-mono" style={{ color: C.muted, fontSize: "0.6rem" }}>READ-ONLY</span>
        {open ? <ChevronDown style={{ width: 13, height: 13, color: C.muted }} /> : <ChevronRight style={{ width: 13, height: 13, color: C.muted }} />}
      </button>
      {open && (
        <pre className="font-mono overflow-auto" style={{ color: "#34D399", fontSize: "0.72rem", lineHeight: 1.7, padding: "14px 16px", maxHeight: 240 }}>
          {JSON.stringify(json, null, 2)}
        </pre>
      )}
    </div>
  );
}

// ─── Structure Mode Toggle ────────────────────────────────────────────────────
function StructureToggle({ detailed, onChange }: { detailed: boolean; onChange: (v: boolean) => void }) {
  return (
    <div className="flex items-center gap-1 rounded-lg p-0.5" style={{ background: C.glassBg, border: `1px solid ${C.glassBorder}` }}>
      {[false, true].map(val => (
        <button key={String(val)} onClick={() => onChange(val)} className="font-mono rounded-md px-3 py-1.5 transition-all"
          style={{ background: detailed === val ? "rgba(16,185,129,0.14)" : "transparent", border: detailed === val ? "1px solid rgba(16,185,129,0.35)" : "1px solid transparent", color: detailed === val ? C.em : C.muted, fontSize: "0.62rem", fontWeight: 700 }}>
          {val ? "Detailed" : "High-Level"}
        </button>
      ))}
    </div>
  );
}

// ─── Flow Indicator ────────────────────────────────────────────────��──────────
function FlowIndicator({ rule }: { rule: LogicRule | null }) {
  if (!rule) return null;
  return (
    <div className="flex items-center gap-3 px-4 py-2.5 rounded-xl" style={{ background: "rgba(16,185,129,0.07)", border: "1px solid rgba(16,185,129,0.22)", boxShadow: "0 0 14px rgba(16,185,129,0.08)" }}>
      <div className="flex items-center gap-1.5">
        <FileCode2 style={{ width: 12, height: 12, color: C.info }} />
        <span className="font-mono" style={{ color: C.info, fontSize: "0.65rem", fontWeight: 700 }}>{rule.source}</span>
      </div>
      <div className="flex items-center gap-1">
        <div style={{ width: 18, height: 1, background: `linear-gradient(90deg, ${C.info}, ${C.em})` }} />
        <Zap style={{ width: 11, height: 11, color: C.em }} />
        <div style={{ width: 18, height: 1, background: `linear-gradient(90deg, ${C.em}, ${C.em2})` }} />
      </div>
      <div className="flex items-center gap-1.5">
        <Layers style={{ width: 12, height: 12, color: C.em }} />
        <span className="font-mono" style={{ color: C.em, fontSize: "0.65rem", fontWeight: 700, textShadow: C.emTextGlow }}>{rule.target}</span>
      </div>
      <div className="ml-auto">
        <span className="font-mono px-2 py-0.5 rounded" style={{ background: C.emDim, border: "1px solid rgba(16,185,129,0.28)", color: C.em, fontSize: "0.58rem", fontWeight: 700, letterSpacing: "0.08em" }}>
          ACTIVE RULE
        </span>
      </div>
    </div>
  );
}

// ─── Main Export ──────────────────────────────────────────────────────────────
export function ProcessingLogicWindow() {
  const [selectedEdiId, setSelectedEdiId] = useState<string | null>(null);
  const [detailedMode, setDetailedMode]   = useState(false);
  const [targetFormat, setTargetFormat]   = useState<"XML" | "JSON">("XML");
  const [instruction, setInstruction]     = useState("Populate the Member tag in XML according to the 2000 loop in EDI 834.");
  const [rules, setRules]                 = useState<LogicRule[]>(INITIAL_RULES);
  const [processing, setProcessing]       = useState(false);
  const [showPreview, setShowPreview]     = useState(false);

  const highlightedTargetIds = useMemo((): Set<string> => {
    if (!selectedEdiId) return new Set();
    function findNode(nodes: EDINode[], id: string): EDINode | null {
      for (const n of nodes) { if (n.id === id) return n; if (n.children) { const f = findNode(n.children, id); if (f) return f; } }
      return null;
    }
    const node = findNode(EDI_TREE_DATA, selectedEdiId);
    if (!node) return new Set();
    return new Set(getTargetMappings(node));
  }, [selectedEdiId]);

  const highlightedEdiIds = useMemo((): Set<string> => new Set(rules.filter(r => r.sourceLoopId).map(r => r.sourceLoopId!)), [rules]);

  const activeRule = useMemo(() => {
    if (!selectedEdiId) return null;
    return rules.find(r => r.sourceLoopId === selectedEdiId) ?? null;
  }, [selectedEdiId, rules]);

  const handleGenerate = useCallback(() => {
    setProcessing(true);
    setTimeout(() => {
      const newRule: LogicRule = {
        id: `r${Date.now()}`, source: "EDI Loop 2000", target: `${targetFormat} Member`,
        operation: "Create node for each loop instance", confirmed: false,
        sourceLoopId: "loop-2000", targetNodeId: "member",
      };
      setRules(prev => {
        const exists = prev.some(r => r.source === newRule.source && r.target === newRule.target);
        return exists ? prev : [newRule, ...prev];
      });
      setProcessing(false);
    }, 1200);
  }, [instruction, targetFormat]);

  const confirmRule = (id: string) => setRules(prev => prev.map(r => r.id === id ? { ...r, confirmed: true } : r));
  const removeRule  = (id: string) => setRules(prev => prev.filter(r => r.id !== id));
  const targetTree  = targetFormat === "XML" ? XML_TARGET : JSON_TARGET;

  return (
    <>
      {/* ── Translation Preview Overlay (portal-like fixed layer) ── */}
      {showPreview && (
        <TranslationPreviewOverlay
          targetFormat={targetFormat}
          onClose={() => setShowPreview(false)}
        />
      )}

      <div style={{ display: "flex", flexDirection: "column", height: "100%", overflow: "hidden" }}>
        {/* ── Top Bar ── */}
        <div
          className="flex items-center gap-4 px-6 py-3 flex-shrink-0"
          style={{ borderBottom: `1px solid ${C.glassBorder}`, background: C.glassBg }}
        >
          <div className="flex items-center gap-2">
            <Layers style={{ width: 15, height: 15, color: C.em }} />
            <span className="font-mono" style={{ color: C.text, fontSize: "0.8rem", fontWeight: 700 }}>
              Processing Logic Configuration
            </span>
            <span className="font-mono px-2 py-0.5 rounded" style={{ background: C.emDim, border: "1px solid rgba(16,185,129,0.30)", color: C.em, fontSize: "0.58rem", fontWeight: 700, letterSpacing: "0.08em" }}>
              {rules.filter(r => r.confirmed).length}/{rules.length} CONFIRMED
            </span>
          </div>

          <div className="ml-auto flex items-center gap-3">
            <StructureToggle detailed={detailedMode} onChange={setDetailedMode} />

            {/* Format toggle */}
            <div className="flex items-center gap-1 rounded-lg p-0.5" style={{ background: C.glassBg, border: `1px solid ${C.glassBorder}` }}>
              {(["XML", "JSON"] as const).map(fmt => (
                <button key={fmt} onClick={() => setTargetFormat(fmt)} className="font-mono rounded-md px-3 py-1.5 transition-all"
                  style={{ background: targetFormat === fmt ? C.purpleDim : "transparent", border: targetFormat === fmt ? "1px solid rgba(139,92,246,0.38)" : "1px solid transparent", color: targetFormat === fmt ? C.purple : C.muted, fontSize: "0.62rem", fontWeight: 700 }}>
                  {fmt}
                </button>
              ))}
            </div>

            {/* Preview Translation Button */}
            <button
              onClick={() => setShowPreview(true)}
              className="flex items-center gap-2 px-4 py-2 rounded-xl font-mono transition-all hover:scale-105"
              style={{
                background: "rgba(16,185,129,0.12)",
                border: "1px solid rgba(16,185,129,0.40)",
                color: C.em, fontSize: "0.7rem", fontWeight: 700,
                boxShadow: `0 0 18px rgba(16,185,129,0.15)`,
                textShadow: C.emTextGlow,
              }}
            >
              <Eye style={{ width: 13, height: 13 }} />
              Preview Translation
            </button>
          </div>
        </div>

        {/* ── Main Three-Panel Workspace ── */}
        <div style={{ flex: 1, minHeight: 0, overflow: "hidden" }}>
          <PanelGroup direction="horizontal" style={{ height: "100%" }}>

            {/* LEFT: EDI Source Structure */}
            <Panel defaultSize={26} minSize={18}>
              <div style={{ height: "100%", display: "flex", flexDirection: "column", borderRight: `1px solid ${C.glassBorder}` }}>
                <div className="flex items-center gap-2 px-4 py-3 flex-shrink-0" style={{ borderBottom: `1px solid ${C.glassBorder}`, background: "rgba(59,130,246,0.05)" }}>
                  <FileCode2 style={{ width: 13, height: 13, color: C.info }} />
                  <span className="font-mono" style={{ color: C.info, fontSize: "0.68rem", fontWeight: 700, letterSpacing: "0.08em" }}>EDI SOURCE</span>
                  <span className="ml-auto font-mono px-2 py-0.5 rounded" style={{ background: "rgba(59,130,246,0.1)", border: "1px solid rgba(59,130,246,0.25)", color: C.info, fontSize: "0.55rem", fontWeight: 700 }}>834 / X12</span>
                </div>

                {selectedEdiId && (
                  <div className="mx-3 mt-2.5 px-3 py-2 rounded-lg flex items-center gap-2 flex-shrink-0" style={{ background: C.infoDim, border: "1px solid rgba(59,130,246,0.25)" }}>
                    <ArrowRight style={{ width: 10, height: 10, color: C.info, flexShrink: 0 }} />
                    <span style={{ color: C.info, fontSize: "0.62rem" }}>Highlighted target nodes synced</span>
                  </div>
                )}

                <div className="overflow-y-auto flex-1 p-3" style={{ scrollbarWidth: "thin" }}>
                  {EDI_TREE_DATA.map(node => (
                    <EDITreeNode key={node.id} node={node} depth={0} selectedId={selectedEdiId} onSelect={setSelectedEdiId} highlightIds={highlightedEdiIds} detailedMode={detailedMode} />
                  ))}
                </div>

                {selectedEdiId && (
                  <button onClick={() => setSelectedEdiId(null)} className="mx-3 mb-3 py-1.5 rounded-lg font-mono flex-shrink-0" style={{ background: C.glassBg, border: `1px solid ${C.glassBorder}`, color: C.muted, fontSize: "0.62rem" }}>
                    Clear Selection
                  </button>
                )}
              </div>
            </Panel>

            <PanelResizeHandle style={{ width: 4, background: C.glassBorder, cursor: "col-resize" }} />

            {/* CENTER: Processing Logic Editor */}
            <Panel defaultSize={40} minSize={28}>
              <div style={{ height: "100%", display: "flex", flexDirection: "column" }}>
                <div className="flex items-center gap-2 px-4 py-3 flex-shrink-0" style={{ borderBottom: `1px solid ${C.glassBorder}`, background: "rgba(16,185,129,0.04)" }}>
                  <Sparkles style={{ width: 13, height: 13, color: C.em }} />
                  <span className="font-mono" style={{ color: C.em, fontSize: "0.68rem", fontWeight: 700, letterSpacing: "0.08em" }}>PROCESSING LOGIC</span>
                </div>

                <div className="flex-1 overflow-y-auto p-4 space-y-4" style={{ scrollbarWidth: "thin" }}>
                  {/* Natural language editor */}
                  <div className="rounded-xl overflow-hidden" style={{ border: "1px solid rgba(16,185,129,0.28)" }}>
                    <div className="flex items-center gap-2 px-4 py-2.5" style={{ background: "rgba(16,185,129,0.08)", borderBottom: "1px solid rgba(16,185,129,0.18)" }}>
                      <Edit3 style={{ width: 11, height: 11, color: C.em }} />
                      <span className="font-mono" style={{ color: C.em, fontSize: "0.62rem", fontWeight: 700, letterSpacing: "0.08em" }}>LOGIC INSTRUCTION</span>
                    </div>
                    <textarea
                      value={instruction}
                      onChange={e => setInstruction(e.target.value)}
                      placeholder="Describe the transformation in plain language…"
                      className="w-full font-mono outline-none resize-none"
                      style={{ background: "rgba(4,9,20,0.55)", color: C.text, fontSize: "0.82rem", lineHeight: 1.7, padding: "14px 16px", minHeight: 90, border: "none" }}
                    />
                    <div className="flex items-center gap-3 px-4 py-2.5" style={{ background: "rgba(4,9,20,0.35)", borderTop: "1px solid rgba(16,185,129,0.12)" }}>
                      <span style={{ color: C.muted, fontSize: "0.65rem" }}>{instruction.length} chars</span>
                      <button
                        onClick={handleGenerate}
                        disabled={processing || !instruction.trim()}
                        className="ml-auto flex items-center gap-2 px-4 py-2 rounded-lg font-mono transition-all hover:scale-105"
                        style={{
                          background: processing ? "rgba(16,185,129,0.08)" : C.em,
                          border: `1px solid ${processing ? "rgba(16,185,129,0.30)" : "transparent"}`,
                          color: processing ? C.em : "#fff",
                          fontSize: "0.7rem", fontWeight: 700,
                          boxShadow: !processing ? `0 0 16px ${C.emGlow}` : "none",
                          opacity: !instruction.trim() ? 0.5 : 1,
                        }}
                      >
                        {processing
                          ? <><div className="w-3 h-3 rounded-full border-2 border-t-transparent animate-spin" style={{ borderColor: `rgba(16,185,129,0.25)`, borderTopColor: C.em }} />Generating…</>
                          : <><Play style={{ width: 11, height: 11 }} />Generate Rules</>
                        }
                      </button>
                    </div>
                  </div>

                  {activeRule && <FlowIndicator rule={activeRule} />}

                  <div>
                    <div className="flex items-center justify-between mb-2.5">
                      <span className="font-mono" style={{ color: C.muted, fontSize: "0.65rem", fontWeight: 700, letterSpacing: "0.08em" }}>INTERPRETED RULES · {rules.length}</span>
                      <span className="font-mono px-2 py-0.5 rounded" style={{ background: "rgba(16,185,129,0.08)", border: "1px solid rgba(16,185,129,0.22)", color: C.em, fontSize: "0.58rem", fontWeight: 700 }}>
                        {rules.filter(r => r.confirmed).length} CONFIRMED
                      </span>
                    </div>
                    <div className="space-y-2.5">
                      {rules.map(rule => (
                        <LogicRuleCard
                          key={rule.id} rule={rule}
                          onConfirm={confirmRule} onRemove={removeRule}
                          isHighlighted={!!selectedEdiId && (rule.sourceLoopId === selectedEdiId || flattenIds(EDI_TREE_DATA.find(n => n.id === selectedEdiId) ?? { id: "", name: "", type: "segment" }).includes(rule.sourceLoopId ?? ""))}
                        />
                      ))}
                      {rules.length === 0 && (
                        <div className="py-8 text-center rounded-xl" style={{ border: `1px dashed ${C.glassBorder}`, color: C.muted, fontSize: "0.75rem" }}>
                          No rules yet — write an instruction and click Generate
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </Panel>

            <PanelResizeHandle style={{ width: 4, background: C.glassBorder, cursor: "col-resize" }} />

            {/* RIGHT: Target Structure + Config Preview */}
            <Panel defaultSize={34} minSize={22}>
              <div style={{ height: "100%", display: "flex", flexDirection: "column", borderLeft: `1px solid ${C.glassBorder}` }}>
                <div className="flex items-center gap-2 px-4 py-3 flex-shrink-0" style={{ borderBottom: `1px solid ${C.glassBorder}`, background: "rgba(139,92,246,0.05)" }}>
                  <Code2 style={{ width: 13, height: 13, color: C.purple }} />
                  <span className="font-mono" style={{ color: C.purple, fontSize: "0.68rem", fontWeight: 700, letterSpacing: "0.08em" }}>TARGET · {targetFormat}</span>
                  {highlightedTargetIds.size > 0 && (
                    <span className="ml-auto font-mono px-2 py-0.5 rounded animate-pulse" style={{ background: C.emDim, border: "1px solid rgba(16,185,129,0.35)", color: C.em, fontSize: "0.55rem", fontWeight: 700 }}>
                      {highlightedTargetIds.size} SYNCED
                    </span>
                  )}
                </div>

                {highlightedTargetIds.size > 0 && (
                  <div className="mx-3 mt-2.5 px-3 py-2 rounded-lg flex items-center gap-2 flex-shrink-0" style={{ background: C.emDim, border: "1px solid rgba(16,185,129,0.28)" }}>
                    <Zap style={{ width: 10, height: 10, color: C.em, flexShrink: 0 }} />
                    <span style={{ color: C.em, fontSize: "0.62rem" }}>Synced from EDI selection</span>
                  </div>
                )}

                <div className="flex-1 overflow-y-auto p-3" style={{ scrollbarWidth: "thin" }}>
                  <TargetTreeNode node={targetTree} depth={0} highlightIds={highlightedTargetIds} detailedMode={detailedMode} />
                </div>

                <div className="p-3 flex-shrink-0" style={{ borderTop: `1px solid ${C.glassBorder}` }}>
                  <BackendJSONPreview rules={rules} targetFormat={targetFormat} />
                </div>
              </div>
            </Panel>

          </PanelGroup>
        </div>
      </div>
    </>
  );
}
